// Cross-language contract test: real backend stream bodies (generated by the
// FastAPI app with fake Google adapters) must pass the frontend's production
// NDJSON reader and runtime validators. Catches drift that generated types
// alone cannot (e.g. defaults, discriminators, datetime formats).

import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { readPlanStream } from "../../lib/v2/ndjson.ts";
import type { VStreamEvent } from "../../lib/v2/validate.ts";

const backend = fileURLToPath(new URL("../../../backend/", import.meta.url));
const venv = `${backend}.venv/bin/python`;
const python = process.env.PYTHON ?? (existsSync(venv) ? venv : "python");

const proc = spawnSync(python, ["-m", "tests.sample_streams"], {
  cwd: backend,
  env: { ...process.env, APP_ENV: "test", PYTHONPATH: "." },
  encoding: "utf8",
  maxBuffer: 10 * 1024 * 1024,
});
if (proc.status !== 0) throw new Error(`backend sample generation failed: ${proc.stderr}`);
const samples = JSON.parse(proc.stdout) as Record<string, string> & Record<"suggestions" | "select_city" | "select_place", unknown>;

async function parse(name: string) {
  const text = samples[name];
  const first = JSON.parse(text.split("\n")[0]);
  const events: VStreamEvent[] = [];
  const stream = new ReadableStream<Uint8Array>({
    start(c) {
      c.enqueue(new TextEncoder().encode(text));
      c.close();
    },
  });
  const end = await readPlanStream(stream, { operationId: first.operation_id, inputRevision: first.input_revision }, (e) => events.push(e));
  return { end, events };
}

test("complete stream from the backend validates end to end", async () => {
  const { end, events } = await parse("complete");
  assert.equal(end.kind, "terminal");
  assert.deepEqual(events.map((e) => e.type).slice(0, 4), ["operation_start", "phase_start", "phase_complete", "phase_start"]);
  if (end.kind === "terminal" && end.event.outcome.outcome_type === "plan") {
    const plan = end.event.outcome.result;
    assert.equal(plan.result_type, "complete");
    const stops = plan.timeline.filter((i) => i.item_type === "stop");
    assert.equal(stops[1].stay_minutes, 45);
    assert.equal(stops[1].hours_detail?.hours_source, "weekly");
    assert.ok(plan.warnings.some((w) => w.code === "outside_city_area" && w.affects_instance_id === "c"));
  } else assert.fail("expected plan outcome");
});

test("partial, error and timeout outcomes validate with their details", async () => {
  const partial = await parse("partial");
  assert.ok(partial.end.kind === "terminal" && partial.end.event.outcome.outcome_type === "plan" && partial.end.event.outcome.result.result_type === "partial");
  const error = await parse("error");
  assert.ok(error.end.kind === "terminal" && error.end.event.outcome.outcome_type === "error");
  if (error.end.kind === "terminal" && error.end.event.outcome.outcome_type === "error") {
    assert.deepEqual(error.end.event.outcome.details?.instance_ids, ["b"]);
    assert.equal(error.end.event.outcome.details?.moved_place_id, "ChIJnew");
  }
  const timeout = await parse("timeout");
  assert.ok(timeout.end.kind === "terminal" && timeout.end.event.outcome.outcome_type === "timeout" && timeout.end.event.outcome.partial !== null);
});

test("suggestion and selection payloads from the backend validate", async () => {
  const { suggestions, selectedCity, selectedPlace } = await import("../../lib/v2/validate.ts");
  const s = suggestions(samples.suggestions);
  assert.equal(s.suggestions[0].place_id, "ChIJdublin");
  const c = selectedCity(samples.select_city);
  assert.equal(c.timezone, "Europe/Dublin");
  assert.ok(c.viewport && c.viewport.low_lat < c.viewport.high_lat);
  const p = selectedPlace(samples.select_place);
  assert.equal(p.timezone, "Europe/Dublin");
});
